name: Docker build test

on:
  push:

jobs:
  build:
    if: github.repository == 'nr23730/fhirspark'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Dockerfile
        run: docker build .
