name: Docker Image CI

on:
  push:
    branches: [ latest-docker ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_URL }}/cbioportal/fhirspark:latest --label maintainer="Niklas Reimer <${{ secrets.EMAIL }}>"
    - name: Login to Docker registry
      run: echo ${{ secrets.ROBOT_TOKEN }} | docker login -u ${{ secrets.ROBOT_NAME }} --password-stdin ${{ secrets.DOCKER_URL }}
    - name: Upload Docker image
      run: docker push ${{ secrets.DOCKER_URL }}/cbioportal/fhirspark:latest
